apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver-nodeport
  namespace: mlops
  labels:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/component: webserver
    app.kubernetes.io/managed-by: custom
spec:
  type: NodePort
  selector:
    component: webserver
    release: airflow
    tier: airflow
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30443

